### ISSUE TITLE
If there is no content in the tab - should it create a .txt file

### ISSUE THREAD

**Issue by HayleyMills** [CLOSER-Cohorts/archivist-utilities#42] opened 2024-08-14 12:09 UTC
For example, if there are no rows completed for the DV tab, I'm not sure why it is creating a dv text file? It is creating a file with content as it is adding the dataset name? - I'm not sure why or where it is picking this up from, as there is nothing in the DV tab?

[mcs1_all_mappings_June24_AP.xlsx](https://github.com/user-attachments/files/16612698/mcs1_all_mappings_June24_AP.xlsx)

[mcs1_cm_interview_dv.txt](https://github.com/user-attachments/files/16612694/mcs1_cm_interview_dv.txt)
[mcs1_proxy_partner_interview_dv.txt](https://github.com/user-attachments/files/16612696/mcs1_proxy_partner_interview_dv.txt)
[mcs1_parent_interview_dv.txt](https://github.com/user-attachments/files/16612700/mcs1_parent_interview_dv.txt)
[mcs1_parent_cm_interview_dv.txt](https://github.com/user-attachments/files/16612702/mcs1_parent_cm_interview_dv.txt)
[mcs1_family_interview_dv.txt](https://github.com/user-attachments/files/16612704/mcs1_family_interview_dv.txt)
[mcs1_cm_derived_dv.txt](https://github.com/user-attachments/files/16612706/mcs1_cm_derived_dv.txt)
[mcs1_family_derived_dv.txt](https://github.com/user-attachments/files/16612708/mcs1_family_derived_dv.txt)
[mcs1_hhgrid_dv.txt](https://github.com/user-attachments/files/16612710/mcs1_hhgrid_dv.txt)
[mcs1_parent_derived_dv.txt](https://github.com/user-attachments/files/16612711/mcs1_parent_derived_dv.txt)
[mcs1_geographically_linked_data_dv.txt](https://github.com/user-attachments/files/16612712/mcs1_geographically_linked_data_dv.txt)

**Comment by HayleyMills** [comment] 2024-08-14 14:02
Related to this and kind of mentioned above, the dataset prefix, is not being picked up from the spreadsheet? I'm not sure where it's coming from? e.g. 
[mcs2_all_mappings_july24_AP.xlsx](https://github.com/user-attachments/files/16614244/mcs2_all_mappings_july24_AP.xlsx)
![image](https://github.com/user-attachments/assets/45451133-e716-41d5-a334-8be15099a31b)


[mcs2_family_derived_dv.txt](https://github.com/user-attachments/files/16614246/mcs2_family_derived_dv.txt)
![image](https://github.com/user-attachments/assets/1ebccb64-3f7a-4f8f-8679-b66a11d06406)

**Comment by HayleyMills** [comment] 2024-08-14 15:05
Yes it's possible, I attached the example. It's creating content for the DVs, even though it's empty! I would have thought it would have removed rows which don't have content (all columns) and so it would have created the dv.txt, but it would have been empty.

**Comment by HayleyMills** [comment] 2024-08-14 16:06
I just want it to be consistent across the two tabs and the readme. For the QV if there are not all the columns required in the spreadsheet populated, as expected it removes these and so if there aren't any rows left after this, it creates a file but it's empty.  So the DV should do the same, instead it's creating rows which don't exist, from somewhere I don't know.

**Comment by ollylucl** [comment] 2024-08-15 09:20
How does the code know if a DV worksheet is present or not?

The worksheets can have arbitrary labels, so my code currently assumes that a DV worksheet is always present, and it is always the second worksheet. 

If the DV worksheet won't have a specific title, and it may or may not be the second worksheet in the file, how would the code know if the DV worksheet is present? Would it assume that if the second worksheet contained columns with the titles 'Dataset prefix', 'Derived variable name', and 'Source variable name', that worksheet is 100% certain to be the DV worksheet? Is it possible that a worksheet that wasn't the DV worksheet could contain columns with those names?

The rules around how to identify worksheets in the Excel file are becoming a bit complex; do they have to be this complex? ie would it be possible to assign fixed labels to the DV worksheet, QV and TV worksheet, etc? ie they must always have a certain label? Or can we guarantee that the DV worksheet is always present, and is always the second worksheet? 

If the complexity around how the code can identify worksheets is unavoidable that's fine, but we should avoid that complexity if at all possible. It increases the complexity of the code, makes the code more difficult to understand, and is a potential source of future bugs.

**Comment by HayleyMills** [comment] 2024-08-15 09:45
Apologies for any crossed wires, if the issue is that there is no DV tab, that's fine, we can make sure it's included. Can you just add it to the readme please. 

I assumed if it picked up the second tab as the DV, then it would expect the headers 'Dataset prefix', 'Derived variable name', and 'Source variable name', and when it couldn't find them (because there is no DV tab, the next tab doesn't have those headers), then it would fail, or produce an empty dv.txt? 

It's not complex - we can stick with "there must be a dv tab" even if empty - I just didn't know that was the case. 

My main concern, is where it pulling the content for the dv.txt from, it pulled it from somewhere when there was no DV tab (I can't tell where), and it created false content in the second example, where there was a DVs tab.

**Comment by ollylucl** [comment] 2024-08-15 10:25
@HayleyMills The DV tab in the mcs2_all_mappings_july24_AP.xlsx file that you uploaded on the second comment on this issue has two dataset_prefix columns. Is this correct? Can worksheets contain multiple columns with the same name? Why are there two dataset_prefix columns, e.g. do the variables belong to two datasets? The code for the archivist utility assumes that column names are unique within a single worksheet, is that not the case? That might explain some of the odd results you're seeing.

**Comment by HayleyMills** [comment] 2024-08-15 10:32
Yes that's correct, and that's what it's like in the template this is based on 
[mappings_wip_template.xlsx](https://github.com/user-attachments/files/16624295/mappings_wip_template.xlsx) and is documented here https://wiki.ucl.ac.uk/display/CTTEAM/Mappings and here https://ucldata.atlassian.net/wiki/spaces/CLOS/pages/37323492/Using+Txt+Files

We can't assume they are the same, although they very nearly always are. It is preferable that the script uses the information that's there.

**Comment by ollylucl** [comment] 2024-08-15 10:41
Ah ok. I was working from the specification at https://ucldata.atlassian.net/wiki/spaces/CLOS/pages/37323492/Using+Txt+Files, that document doesn't give the specific column locations in worksheets, whereas the specification at https://wiki.ucl.ac.uk/pages/viewpage.action?pageId=327029042 does.

**Comment by ollylucl** [comment] 2024-08-15 10:43
Based on the presence of specific column locations in https://wiki.ucl.ac.uk/pages/viewpage.action?pageId=327029042, can you confirm that the columns in worksheets will have a particular order? e.g. if a DV worksheet is present, it will always have a specific set of columns in a particular order?

**Comment by HayleyMills** [comment] 2024-08-15 10:49
Both of those links have the same columns in the same order- so I'm not sure what you mean? Yes they will follow the template.

**Comment by ollylucl** [comment] 2024-08-15 12:13
From https://ucldata.atlassian.net/wiki/spaces/CLOS/pages/37323492/Using+Txt+Files:

```
dv.txt

Mapping file which links derived variables to source variables.

Tab delimited

4 columns:

1. Dataset prefix
2. Derived variable name
3. Dataset prefix

4. Source variable name
```
From https://wiki.ucl.ac.uk/pages/viewpage.action?pageId=327029042:
```
dv.txt

1. Dataset prefix = Template DV A

2. Derived variable name = Template DV B

3. Dataset prefix = Template DV D

4. Source variable name= Template DV E
```

The wiki page in the second link is specifying the letters that identifiy the precise columns in the Excel worksheet we need to use, e.g. Template DV A, Template DV B, Template DV E.

The wiki page in the first link, which I was working from, doesn't specify columns in the same way.

Because the wiki page in the second link is being more precise about the location of columns, that suggests that if a worksheet is present, it will have a specific set of columns, in a specific order. Can you confirm that this is the case? In order to create the mapping files as described in the second wiki page, my code will have to start selecting columns based on their position, and not by their name as it currently does.

It seems less than ideal to me that the dv worksheet has multiple columns with the same name but which represent different things; is there any way to give the two dataset prefix columns in the dv worksheet unique names?

**Comment by HayleyMills** [comment] 2024-08-15 15:45
It really doesn't matter - however it's working on the other sheets is fine. If you want to use the headers, we can do that. 
I'm not sure the significance of the wiki pages, I created the internal wiki with the locations, specifically to help with this, so not sure why you were using the other one. We also had a discussions around whether it was using locations or headers, which you clarified.  
We create the template, so we can do whatever we want with it. If it's easier for the column headers to be different in the DV, I'll just update the spreadsheet. 
As I've said before, it doesn't matter how it works, as long as we know how it works and it's in the readme.

**Comment by ollylucl** [comment] 2024-08-19 13:16
`"Apologies for any crossed wires, if the issue is that there is no DV tab, that's fine, we can make sure it's included. Can you just add it to the readme please."`

The Readme already specifies that the DV tab must be present, although it doesn't need to have a specific name: _"The worksheet containing data from which the dv mappings are created MUST be the second worksheet in the file. This worksheet can have any name."_ 

When I asked earlier in this thread if it was possible that the uploaded spreadsheet may not contain DV data in the second spreadsheet, I wanted to know if such a spreadsheet should be considered valid input by the application. We can take it as given that a spreadsheet missing that worksheet could be uploaded (after all users can upload any file they want) but I wanted to know whether or not the application should consider that spreadsheet valid input and process it anyway, process it partially, or reject it outright as invalid.

`"I'm not sure the significance of the wiki pages, I created the internal wiki with the locations, specifically to help with this, so not sure why you were using the other one."`

I'm using that wiki page because you told me to in various emails (e.g. do a search for emails with the title 'Mappings excel to text files').

`"It really doesn't matter - however it's working on the other sheets is fine. If you want to use the headers, we can do that. We also had a discussions around whether it was using locations or headers, which you clarified. We create the template, so we can do whatever we want with it. If it's easier for the column headers to be different in the DV, I'll just update the spreadsheet. As I've said before, it doesn't matter how it works, as long as we know how it works and it's in the readme."`

Fair enough, but it's been stated at several points previously that it wouldn't be ideal that we insist that all input data to the application has a specific structure. e.g. in https://github.com/CLOSER-Cohorts/archivist-utilities/issues/6:

_"Having everything identical to the template is not ideal, as we need to edit the file to get it to work, which takes the same amount of time as it does to create the .txt files. This is because everything returning from the studies now, didn't follow this new template, going forward it will be used, but for now that's not the case."_

My preference would be that all spreadsheets must use names for the tabs/columns as specified in the template, because that's the easiest way to write an application that is good at error handling and behaves in a predictable way whatever input you give it. However, that might not be what you want, e.g. in https://wiki.ucl.ac.uk/display/CTTEAM/Mappings it says that we might want to 'hide columns'; I'm not sure what exactly that means but if it meant hiding/deleting column names, that wouldn't be compatible with code that used column names to select data.  

Sorry to keep going back to this issue about whether or not the input should have a particular structure, but at several points I've been told it shouldn't, and at several other points I've been told it should. A decision needs to be made while being aware of the trade-offs involved. If we can't assume that the input spreadsheet has a particular structure/naming convention for the reasons you've given in previous emails and GitHub issues, we can't perform automatic input validation. The responsibility for ensuring the validity of input will fall on the human user. It's ok if that's something you're willing to put up with, as long as you're aware of the trade-off involved.

**Comment by HayleyMills** [comment] 2024-08-19 13:33
@ollylucl ok, thanks for pointing out the dv part of the readme, I missed it, so I'll make this clearer. 

I'm not sure how productive it is pulling out sentences from previous issues, which have been taken out of context. 

If a comment is several paragraphs long - maybe it's more productive to have a chat instead, to avoid confusion. 

If you would like me to be more prescriptive in how it should work for this and for future scripts, I can do, but that might not be the best or easiest way for you. 

For this issue - do want the template headers in the DV to be updated or not?

**Comment by ollylucl** [comment] 2024-08-27 13:32
I've modified the code in https://github.com/CLOSER-Cohorts/archivist-utilities/pull/48 so that if a column isn't present in a worksheet, the code wouldn't add any rows containing 'undefined' to the output file(s).

We can further improve error handling by reporting an error to the user if the input worksheet doesn't have a particular structure (i.e. worksheets with particular titles, and columns in those worksheets with a particular title). I'll create a new issue for that.

**Comment by ollylucl** [comment] 2024-09-17 08:08
I'm closing this issue as https://github.com/CLOSER-Cohorts/archivist-utilities/pull/48 and https://github.com/CLOSER-Cohorts/archivist-utilities/pull/49 have addressed the problems raised around _dv files being generated when there was no DV tab in the input spreadsheet and 'undefined' values appearing in the generated text files.

I've created a new issue https://github.com/CLOSER-Cohorts/archivist-utilities/issues/50 which will modify the code so it enforces a particular structure for the input spreadsheet. This will help error-checking, and deal with other problems raised in this issue around things like not properly handling missing worksheets, not picking up the correct dataset prefix, etc.

**Closed by ollylucl** 2024-09-17 08:08 UTC
Labels: bug, question, High priority
